export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const LOG_OUT = 'LOG_OUT';
export const SAVE_SELECTED_INSTANCES = 'SAVE_SELECTED_INSTANCES';
export const ADD_SERVER_LOGS = 'ADD_SERVER_LOGS';
export const REMOVE_SERVER_LOGS = 'REMOVE_SERVER_LOGS';
export const ADD_REQ_LOG = 'ADD_REQ_LOG';
export const REMOVE_REQ_LOG = 'REMOVE_REQ_LOG';

export const LOAD_INSTANCES_SUCCESS = 'LOAD_INSTANCES_SUCCESS';
export const LOAD_INSTANCE_SUCCESS = 'LOAD_INSTANCE_SUCCESS';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const TOGGLE_INSTANCE_SUCCESS = 'TOGGLE_INSTANCE_SUCCESS';
export const LOGS_DIR_SUCCESS = 'LOGS_DIR_SUCCESS';
export const CAT_LOG_SUCCESS = 'CAT_LOG_SUCCESS';
export const GREP_LOG_SUCCESS = 'GREP_LOG_SUCCESS';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';