import webpack from 'webpack';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import baseConfig from './base.config.babel.js';
import path from 'path';


export default baseConfig({
    output: {
        publicPath: '/',
        path: path.resolve(process.cwd(), 'dist'),
        filename: '[name].js',
    },
    devtool: 'cheap-module-eval-source-map',
    performance: {
        hints: false,
    },
    devServer: {
        contentBase: 'src',
        compress: true,
        port: '9001',
        historyApiFallback: true,
        proxy: {
            '/api': {
                target: 'http://localhost:4000',
                secure: false,
                pathRewrite: {"^/api" : ""}
            }
        },
        stats: {
            chunks: false,
            assets: false,
            children: false,
        },
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        // Inject all files that are generated by webpack, e.g. bundle.js
        new HtmlWebpackPlugin({
            inject: true,
            template: 'src/index.html',
        }),
        // Bundle css
        new ExtractTextPlugin('[name].css'),
    ],

});